_BASE_: "meshed_memory.yaml"

###################################### DATALOADER ######################################
DATALOADER:
  TRAIN_BATCH_SIZE: 16

######################################### Engine #########################################
ENGINE:
  NAME: 'RLTrainer'

######################################### MODEL #########################################
MODEL:
  WEIGHTS: '{path_to_xe_model}'

####################################### Optimizer #######################################
SOLVER:
  NAME: 'Adam'
  EPOCH: 60
  BASE_LR: 0.00001
  BETAS: [0.9, 0.999]

####################################### lr scheduler #######################################
LR_SCHEDULER:
  NAME: 'StepLR'
  STEP_SIZE: 10
  GAMMA: 0.8


