_BASE_: "../../mm_understanding_base.yaml"

####################################### DATASETS #######################################
DATASETS:
  TRAIN: 'VCRDataset'
  VAL: 'VCRDataset'
  TEST: ''

######################################### Engine #########################################
ENGINE:
  NAME: 'VCRTrainer'

###################################### DATALOADER ######################################
DATALOADER:
  TRAIN_BATCH_SIZE: 16
  TEST_BATCH_SIZE: 32
  NUM_WORKERS: 4
  FEATS_FOLDER: '../open_source_dataset/VCR/features/up_down'
  ANNO_FOLDER: '../open_source_dataset/VCR'
  SEQ_PER_SAMPLE:  4
  MAX_FEAT_NUM: 51

######################################### MODEL #########################################
MODEL:
  MAX_SEQ_LEN: 38
  WEIGHTS: '../pretrain/TDEN_VCR/vcr_pretrained/TDEN_VCR_pretrained.pth'

######################################### BERT #########################################
  BERT:
    NUM_HIDDEN_LAYERS: 12
    V_NUM_HIDDEN_LAYERS: 6
    NUM_UNDERSTANDING_LAYERS: 6
    NUM_GENERATION_LAYERS: 0
    LAYER_DROP: 0.0
    V_LAYER_DROP: 0.0
    U_LAYER_DROP: 0.0

######################################### MM_PREDICTOR #########################################
  MM_PREDICTOR:
    LABELS_NUM: 1
    POOLER_INPUT_SIZE: 768
    POOLER_OUTPUT_SIZE: 1024
    POOLER_BN: False
    POOLER_DROPOUT: 0.1

####################################### Optimizer #######################################
SOLVER:
  NAME: 'BertAdam'
  EPOCH: 20
  CHECKPOINT_PERIOD: 1
  EVAL_PERIOD: 1
  BASE_LR: 0.00002
  BIAS_LR_FACTOR: 1.0
  WEIGHT_DECAY: 0.01
  WEIGHT_DECAY_NORM: 0.0
  WEIGHT_DECAY_BIAS: 0.0
  MOMENTUM: 0.9
  DAMPENING: 0.0
  NESTEROV: 0.0
  BETAS: [0.9, 0.999]
  EPS: 1e-8
  GRAD_CLIP: -1.0
  GRAD_CLIP_TYPE: 'Norm'
  NORM_TYPE: 2.0
  
####################################### lr scheduler ####################################### 
LR_SCHEDULER:
  NAME: 'WarmupMultiStepLR'
  STEPS: [4, 8]
  GAMMA: 0.1
  WARMUP: 1

####################################### losses ####################################### 
LOSSES:
  NAMES: ['CrossEntropy']

INFERENCE:
  VOCAB: ''
  NAME: 'VCREvaler'
  ID_KEY: 'question_id'
  VALUE: 'answer'
  VAL_ANNFILE: '../open_source_dataset/VCR/val.jsonl'
  TEST_ANNFILE: ''
  GENERATION_MODE: False
