_BASE_: "../base_att_image_caption.yaml"

DATALOADER:
  TRAIN_BATCH_SIZE: 16
  TEST_BATCH_SIZE: 32
  NUM_WORKERS: 4
  
######################################### Engine #########################################
ENGINE:
  NAME: 'RLTrainer'
  
######################################### MODEL #########################################
MODEL:
  WEIGHTS: '../finish_models/attention/model_Epoch_00027_Iter_0095579.pth'
  ENCODER: 'Encoder'
  DECODER: 'SALSTMDecoder'

  SALSTM:
    ATT_EMBED_SIZE: 512
    ATT_EMBED_DROPOUT: 0.0

####################################### Optimizer #######################################
SOLVER:
  NAME: 'Adam'
  EPOCH: 30
  BASE_LR: 0.00005
  
####################################### lr scheduler ####################################### 
LR_SCHEDULER:
  NAME: 'StepLR'
  STEP_SIZE: 10
  GAMMA: 0.8
