_BASE_: "../../uniter_mm_understanding_base.yaml"

####################################### DATASETS #######################################
DATASETS:
  TRAIN: 'Flickr30kDatasetForSingleStream'
  VAL: 'Flickr30kDatasetForSingleStreamVal'
  TEST: 'Flickr30kDatasetForSingleStreamVal'

######################################### Engine #########################################
ENGINE:
  NAME: 'SingleStreamRetrievalTrainer'

###################################### DATALOADER ######################################
DATALOADER:
  TRAIN_BATCH_SIZE: 40
  TEST_BATCH_SIZE: 1
  NUM_WORKERS: 4
  FEATS_FOLDER: '../open_source_dataset/flickr30k/features/up_down'
  ANNO_FOLDER: '../open_source_dataset/flickr30k'
  SEQ_PER_SAMPLE:  1
  MAX_FEAT_NUM: 51
  NEGATIVE_SIZE: 1

######################################### MODEL #########################################
MODEL:
  MAX_SEQ_LEN: 30
  META_ARCHITECTURE: 'UniterRetrieval'
  ENCODER: 'SingleStreamBertEncoder'
  DECODER: ''
  PREDICTOR: 'SingleStreamMultiModalSimilarity'
  WEIGHTS: '../pretrain/UNITER/UNITER.pth'

######################################### MM_PREDICTOR #########################################
  MM_PREDICTOR:
    LABELS_NUM: 1

####################################### Optimizer #######################################
SOLVER:
  NAME: 'Adam'
  EPOCH: 20
  CHECKPOINT_PERIOD: 1
  EVAL_PERIOD: 2
  BASE_LR: 0.00002
  BIAS_LR_FACTOR: 1.0
  WEIGHT_DECAY: 0.0
  WEIGHT_DECAY_NORM: 0.0
  WEIGHT_DECAY_BIAS: 0.0
  MOMENTUM: 0.9
  DAMPENING: 0.0
  NESTEROV: 0.0
  BETAS: [0.9, 0.999]
  EPS: 1e-8
  GRAD_CLIP: 2.0
  GRAD_CLIP_TYPE: 'norm'
  NORM_TYPE: 2.0
  WRITE_PERIOD: 20
  
####################################### lr scheduler ####################################### 
LR_SCHEDULER:
  NAME: 'WarmupMultiStepLR'
  STEPS: [7, 15]
  GAMMA: 0.1
  WARMUP: 2

####################################### losses ####################################### 
LOSSES:
  NAMES: ['Triplet']
  MARGIN: 0.2

INFERENCE:
  VOCAB: ''
  ID_KEY: 'image_id'
  VALUE: 'caption'
  NAME: ''
  VAL_ANNFILE: '../open_source_dataset/flickr30k/all_data_final_val_set0_2014.jsonline'
  TEST_ANNFILE: '../open_source_dataset/flickr30k/all_data_final_test_set0_2014.jsonline'
  GENERATION_MODE: False
  VAL_EVAL_START: 7
  TEST_EVAL_START: 7
