_BASE_: "base_att_image_caption.yaml"

###################################### DATALOADER ######################################
DATALOADER:
  TRAIN_BATCH_SIZE: 12
  TEST_BATCH_SIZE: 32
  NUM_WORKERS: 4
  FEATS_FOLDER: '../open_source_dataset/mscoco_dataset/features/up_down_36'
  ANNO_FOLDER:  '../open_source_dataset/mscoco_dataset'
  RELATION_FILE: '../open_source_dataset/mscoco_dataset/features/relation/relationship_coco.pkl'
  SEQ_PER_SAMPLE:  5
  MAX_FEAT_NUM: 36

######################################### Scheduled sampling #########################################
SCHEDULED_SAMPLING:
  START_EPOCH: 9999
  INC_EVERY_EPOCH: 25
  INC_PROB: 0.05
  MAX_PROB: 0.25

######################################### Engine #########################################
ENGINE:
  NAME: 'RLTrainer'

######################################### MODEL #########################################
MODEL:
  WEIGHTS: '../finish_models/gcn/model_Epoch_00280_Iter_0158479.pth'
  ENCODER: 'GCNEncoder'
  #################################### Visual embedding ####################################
  VISUAL_EMBED:
    NAME: 'VisualIdentityEmbedding'
    IN_DIM: 2048
    OUT_DIM: 2048
  #################################### GCN ####################################
  GCN:
    IN_DIM: 2048
    OUT_DIM: 2048
    RELATION_NUM: 21
    DROPOUT: 0.5
  UPDOWN:
    ATT_EMBED_SIZE: 512
    DROPOUT1: 0.0
    DROPOUT2: 0.0 #0.5
    ATT_EMBED_DROPOUT: 0.0 #0.5

####################################### Optimizer #######################################
SOLVER:
  NAME: 'Adam'
  EPOCH: 60
  CHECKPOINT_PERIOD: 1
  EVAL_PERIOD: 1
  BASE_LR: 0.00005
  BIAS_LR_FACTOR: 1.0
  WEIGHT_DECAY: 0.0
  WEIGHT_DECAY_NORM: 0.0
  WEIGHT_DECAY_BIAS: 0.0
  MOMENTUM: 0.9
  DAMPENING: 0.0
  NESTEROV: 0.0
  BETAS: [0.9, 0.999]
  EPS: 1e-8
  GRAD_CLIP: 0.1
  GRAD_CLIP_TYPE: 'value'
  NORM_TYPE: 2.0

####################################### lr scheduler ####################################### 
LR_SCHEDULER:
  NAME: 'StepLR'
  STEP_SIZE: 30
  GAMMA: 0.8

####################################### losses ####################################### 
LOSSES:
  NAMES: ['CrossEntropy']
